package com.pjtsearch.opencontroller.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0057ce)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd8e2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001947)
val md_theme_light_secondary = Color(0xFF3a5ba9)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd9e2ff)
val md_theme_light_onSecondaryContainer = Color(0xFF00184a)
val md_theme_light_tertiary = Color(0xFF006c51)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF83f8cf)
val md_theme_light_onTertiaryContainer = Color(0xFF002116)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfdfbff)
val md_theme_light_onBackground = Color(0xFF1b1b1d)
val md_theme_light_surface = Color(0xFFfdfbff)
val md_theme_light_onSurface = Color(0xFF1b1b1d)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f4)
val md_theme_light_inverseSurface = Color(0xFF2f3033)
val md_theme_light_inversePrimary = Color(0xFFaec6ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFaec6ff)
val md_theme_dark_onPrimary = Color(0xFF002c71)
val md_theme_dark_primaryContainer = Color(0xFF00419e)
val md_theme_dark_onPrimaryContainer = Color(0xFFd8e2ff)
val md_theme_dark_secondary = Color(0xFFb0c5ff)
val md_theme_dark_onSecondary = Color(0xFF002b76)
val md_theme_dark_secondaryContainer = Color(0xFF1e4390)
val md_theme_dark_onSecondaryContainer = Color(0xFFd9e2ff)
val md_theme_dark_tertiary = Color(0xFF64dbb3)
val md_theme_dark_onTertiary = Color(0xFF003828)
val md_theme_dark_tertiaryContainer = Color(0xFF00513c)
val md_theme_dark_onTertiaryContainer = Color(0xFF83f8cf)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1b1b1d)
val md_theme_dark_onBackground = Color(0xFFe3e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1d)
val md_theme_dark_onSurface = Color(0xFFe3e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1d)
val md_theme_dark_inverseSurface = Color(0xFFe3e2e6)
val md_theme_dark_inversePrimary = Color(0xFF0057ce)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)